package es.upm.babel.ccrv.rw;

/*
 * Test the scenario of readers and writers
 */

// import java.util.concurrent.ThreadLocalRandom;

import es.upm.babel.ccrv.Semaphore;
import es.upm.babel.ccrv.Invariant;

public class TestRW
{
  public static void main(String[] args) {
    RW rw=new RW();
    // First, we create an instance of the outer class (the one that
    // contains the reader and the writer)
    RW.Reader r=rw.new Reader();
    RW.Reader r2=rw.new Reader();
    // The readers...
    RW.Writer w=rw.new Writer();
    RW.Writer w2=rw.new Writer();
    // ... and the writers ...

    // ... and pass the invariant to Semaphore, so from now on, every call
    // an Semaphore (await/signal) checks whether the invariant holds.
    Semaphore.addInvariant(() -> {
        return
          (Semaphore.after("roomEmptyWaitW") - Semaphore.after("roomEmptySignalW") == 1
           &&
           (Semaphore.after("mutexSignalR")- Semaphore.before("mutexWaitR2"))==0)
          ||
          Semaphore.after("roomEmptyWaitW") - Semaphore.after("roomEmptySignalW") == 0;
      });

    r.start(); // Start the reader
    w.start(); // Start the writer
    // r2.start();
    // w2.start();
  } // main

} // class TestRW


//  0:	[11] -> Invariant OK: {croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=0 mutex=1
// 17:	[11] -> Escrito valor: 1
// 17:		[9] -> Invariant OK: {cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=0 mutex=0
// 18:	[11] -> Invariant OK: {cREADERSUP__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=1 mutex=0
// 18:	[11] -> Invariant OK: {cREADERSUP__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitW__m=2, croomEmptyWaitW__p=2} roomEmpty=0 mutex=0
// 19:	[11] -> Escrito valor: 2
// 19:		[9] -> Invariant OK: {cREADERSUP__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitR__m=1, croomEmptyWaitW__m=2, croomEmptyWaitW__p=2} roomEmpty=-1 mutex=0
// 20:		[9] -> Invariant OK: {cREADERSUP__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=2, croomEmptySignalW__p=2, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=2, croomEmptyWaitW__p=2} roomEmpty=0 mutex=0
// 20:	[11] -> Invariant OK: {cREADERSUP__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=2, croomEmptySignalW__p=2, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=2, croomEmptyWaitW__p=2} roomEmpty=0 mutex=0
// 21:		[9] -> Invariant OK: {cREADERSUP__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=2, croomEmptySignalW__p=2, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=2, croomEmptyWaitW__p=2} roomEmpty=0 mutex=1
// 21:		[9] -> Obtenido valor: 2
// 21:	[11] -> Invariant OK: {cREADERSUP__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=2, croomEmptySignalW__p=2, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=3, croomEmptyWaitW__p=2} roomEmpty=-1 mutex=1
// 22:		[9] -> Invariant OK: {cREADERSUP__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=2, croomEmptySignalW__p=2, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=3, croomEmptyWaitW__p=2} roomEmpty=-1 mutex=0
// 23:	[11] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=2, croomEmptySignalW__p=2, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=3, croomEmptyWaitW__p=3} roomEmpty=0 mutex=0
// 23:	[11] -> Escrito valor: 3
// 23:		[9] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=2, croomEmptySignalW__p=2, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=3, croomEmptyWaitW__p=3} roomEmpty=0 mutex=0
// 24:	[11] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=3, croomEmptySignalW__p=3, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=3, croomEmptyWaitW__p=3} roomEmpty=1 mutex=0
// 24:	[11] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=3, croomEmptySignalW__p=3, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=4, croomEmptyWaitW__p=4} roomEmpty=0 mutex=0
// 24:	[11] -> Escrito valor: 4
// 25:		[9] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=1, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=3, croomEmptySignalW__p=3, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=4, croomEmptyWaitW__p=4} roomEmpty=0 mutex=1
// 25:	[11] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=1, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=4, croomEmptySignalW__p=4, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=4, croomEmptyWaitW__p=4} roomEmpty=1 mutex=1
// 26:	[11] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=1, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=4, croomEmptySignalW__p=4, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=5, croomEmptyWaitW__p=5} roomEmpty=0 mutex=1
// 26:	[11] -> Escrito valor: 5
// 26:		[9] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=1, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=2, cmutexWaitR__p=2, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=4, croomEmptySignalW__p=4, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=5, croomEmptyWaitW__p=5} roomEmpty=0 mutex=0
// 27:	[11] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=2, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=2, cmutexWaitR__p=2, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=5, croomEmptySignalW__p=5, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=5, croomEmptyWaitW__p=5} roomEmpty=1 mutex=0
// 27:		[9] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=2, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=2, cmutexWaitR__p=2, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=5, croomEmptySignalW__p=5, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=5, croomEmptyWaitW__p=5} roomEmpty=0 mutex=0
// 28:		[9] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=2, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=2, cmutexWaitR__p=2, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=5, croomEmptySignalW__p=5, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=5, croomEmptyWaitW__p=5} roomEmpty=0 mutex=1
// 28:		[9] -> Obtenido valor: 5
// 28:	[11] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=2, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=1, cmutexWaitR2__p=1, cmutexWaitR__m=2, cmutexWaitR__p=2, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=5, croomEmptySignalW__p=5, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=6, croomEmptyWaitW__p=5} roomEmpty=-1 mutex=1
// 29:		[9] -> Invariant OK: {cREADERSDOWN__p=1, cREADERSUP__p=2, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=2, cmutexWaitR__p=2, croomEmptySignalR__m=1, croomEmptySignalR__p=1, croomEmptySignalW__m=5, croomEmptySignalW__p=5, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=6, croomEmptyWaitW__p=5} roomEmpty=-1 mutex=0
// 29:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=2, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=2, cmutexWaitR__p=2, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=5, croomEmptySignalW__p=5, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=6, croomEmptyWaitW__p=6} roomEmpty=0 mutex=0
// 29:	[11] -> Escrito valor: 6
// 30:		[9] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=2, cmutexSignalR2__m=1, cmutexSignalR2__p=1, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=2, cmutexWaitR__p=2, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=5, croomEmptySignalW__p=5, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=6, croomEmptyWaitW__p=6} roomEmpty=0 mutex=0
// 30:		[9] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=2, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=2, cmutexWaitR__p=2, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=5, croomEmptySignalW__p=5, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=6, croomEmptyWaitW__p=6} roomEmpty=0 mutex=1
// 31:		[9] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=2, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=5, croomEmptySignalW__p=5, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=6, croomEmptyWaitW__p=6} roomEmpty=0 mutex=0
// 31:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=6, croomEmptySignalW__p=6, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=6, croomEmptyWaitW__p=6} roomEmpty=1 mutex=0
// 31:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=6, croomEmptySignalW__p=6, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=7, croomEmptyWaitW__p=7} roomEmpty=0 mutex=0
// 32:	[11] -> Escrito valor: 7
// 32:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=7, croomEmptySignalW__p=7, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=7, croomEmptyWaitW__p=7} roomEmpty=1 mutex=0
// 33:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=7, croomEmptySignalW__p=7, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=8, croomEmptyWaitW__p=8} roomEmpty=0 mutex=0
// 33:	[11] -> Escrito valor: 8
// 33:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=8, croomEmptySignalW__p=8, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=8, croomEmptyWaitW__p=8} roomEmpty=1 mutex=0
// 34:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=8, croomEmptySignalW__p=8, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=9, croomEmptyWaitW__p=9} roomEmpty=0 mutex=0
// 34:	[11] -> Escrito valor: 9
// 34:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=9, croomEmptySignalW__p=9, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=9, croomEmptyWaitW__p=9} roomEmpty=1 mutex=0
// 34:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=9, croomEmptySignalW__p=9, croomEmptyWaitR__m=2, croomEmptyWaitR__p=2, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 34:	[11] -> Escrito valor: 10
// 35:		[9] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=9, croomEmptySignalW__p=9, croomEmptyWaitR__m=3, croomEmptyWaitR__p=2, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=-1 mutex=0
// 35:		[9] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=3, croomEmptyWaitR__p=3, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 36:	[11] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=2, cmutexSignalR__p=2, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=3, croomEmptyWaitR__p=3, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 36:		[9] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=3, cmutexSignalR__p=3, cmutexWaitR2__m=2, cmutexWaitR2__p=2, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=3, croomEmptyWaitR__p=3, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=1
// 36:		[9] -> Obtenido valor: 10
// 36:		[9] -> Invariant OK: {cREADERSDOWN__p=2, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=3, cmutexSignalR__p=3, cmutexWaitR2__m=3, cmutexWaitR2__p=3, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=2, croomEmptySignalR__p=2, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=3, croomEmptyWaitR__p=3, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 37:		[9] -> Invariant OK: {cREADERSDOWN__p=3, cREADERSUP__p=3, cmutexSignalR2__m=2, cmutexSignalR2__p=2, cmutexSignalR__m=3, cmutexSignalR__p=3, cmutexWaitR2__m=3, cmutexWaitR2__p=3, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=3, croomEmptySignalR__p=3, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=3, croomEmptyWaitR__p=3, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 37:		[9] -> Invariant OK: {cREADERSDOWN__p=3, cREADERSUP__p=3, cmutexSignalR2__m=3, cmutexSignalR2__p=3, cmutexSignalR__m=3, cmutexSignalR__p=3, cmutexWaitR2__m=3, cmutexWaitR2__p=3, cmutexWaitR__m=3, cmutexWaitR__p=3, croomEmptySignalR__m=3, croomEmptySignalR__p=3, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=3, croomEmptyWaitR__p=3, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=1
// 38:		[9] -> Invariant OK: {cREADERSDOWN__p=3, cREADERSUP__p=3, cmutexSignalR2__m=3, cmutexSignalR2__p=3, cmutexSignalR__m=3, cmutexSignalR__p=3, cmutexWaitR2__m=3, cmutexWaitR2__p=3, cmutexWaitR__m=4, cmutexWaitR__p=4, croomEmptySignalR__m=3, croomEmptySignalR__p=3, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=3, croomEmptyWaitR__p=3, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 38:		[9] -> Invariant OK: {cREADERSDOWN__p=3, cREADERSUP__p=4, cmutexSignalR2__m=3, cmutexSignalR2__p=3, cmutexSignalR__m=3, cmutexSignalR__p=3, cmutexWaitR2__m=3, cmutexWaitR2__p=3, cmutexWaitR__m=4, cmutexWaitR__p=4, croomEmptySignalR__m=3, croomEmptySignalR__p=3, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=4, croomEmptyWaitR__p=4, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 38:		[9] -> Invariant OK: {cREADERSDOWN__p=3, cREADERSUP__p=4, cmutexSignalR2__m=3, cmutexSignalR2__p=3, cmutexSignalR__m=4, cmutexSignalR__p=4, cmutexWaitR2__m=3, cmutexWaitR2__p=3, cmutexWaitR__m=4, cmutexWaitR__p=4, croomEmptySignalR__m=3, croomEmptySignalR__p=3, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=4, croomEmptyWaitR__p=4, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=1
// 39:		[9] -> Obtenido valor: 10
// 39:		[9] -> Invariant OK: {cREADERSDOWN__p=3, cREADERSUP__p=4, cmutexSignalR2__m=3, cmutexSignalR2__p=3, cmutexSignalR__m=4, cmutexSignalR__p=4, cmutexWaitR2__m=4, cmutexWaitR2__p=4, cmutexWaitR__m=4, cmutexWaitR__p=4, croomEmptySignalR__m=3, croomEmptySignalR__p=3, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=4, croomEmptyWaitR__p=4, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 39:		[9] -> Invariant OK: {cREADERSDOWN__p=4, cREADERSUP__p=4, cmutexSignalR2__m=3, cmutexSignalR2__p=3, cmutexSignalR__m=4, cmutexSignalR__p=4, cmutexWaitR2__m=4, cmutexWaitR2__p=4, cmutexWaitR__m=4, cmutexWaitR__p=4, croomEmptySignalR__m=4, croomEmptySignalR__p=4, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=4, croomEmptyWaitR__p=4, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 40:		[9] -> Invariant OK: {cREADERSDOWN__p=4, cREADERSUP__p=4, cmutexSignalR2__m=4, cmutexSignalR2__p=4, cmutexSignalR__m=4, cmutexSignalR__p=4, cmutexWaitR2__m=4, cmutexWaitR2__p=4, cmutexWaitR__m=4, cmutexWaitR__p=4, croomEmptySignalR__m=4, croomEmptySignalR__p=4, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=4, croomEmptyWaitR__p=4, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=1
// 40:		[9] -> Invariant OK: {cREADERSDOWN__p=4, cREADERSUP__p=4, cmutexSignalR2__m=4, cmutexSignalR2__p=4, cmutexSignalR__m=4, cmutexSignalR__p=4, cmutexWaitR2__m=4, cmutexWaitR2__p=4, cmutexWaitR__m=5, cmutexWaitR__p=5, croomEmptySignalR__m=4, croomEmptySignalR__p=4, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=4, croomEmptyWaitR__p=4, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 41:		[9] -> Invariant OK: {cREADERSDOWN__p=4, cREADERSUP__p=5, cmutexSignalR2__m=4, cmutexSignalR2__p=4, cmutexSignalR__m=4, cmutexSignalR__p=4, cmutexWaitR2__m=4, cmutexWaitR2__p=4, cmutexWaitR__m=5, cmutexWaitR__p=5, croomEmptySignalR__m=4, croomEmptySignalR__p=4, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=5, croomEmptyWaitR__p=5, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 41:		[9] -> Invariant OK: {cREADERSDOWN__p=4, cREADERSUP__p=5, cmutexSignalR2__m=4, cmutexSignalR2__p=4, cmutexSignalR__m=5, cmutexSignalR__p=5, cmutexWaitR2__m=4, cmutexWaitR2__p=4, cmutexWaitR__m=5, cmutexWaitR__p=5, croomEmptySignalR__m=4, croomEmptySignalR__p=4, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=5, croomEmptyWaitR__p=5, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=1
// 41:		[9] -> Obtenido valor: 10
// 41:		[9] -> Invariant OK: {cREADERSDOWN__p=4, cREADERSUP__p=5, cmutexSignalR2__m=4, cmutexSignalR2__p=4, cmutexSignalR__m=5, cmutexSignalR__p=5, cmutexWaitR2__m=5, cmutexWaitR2__p=5, cmutexWaitR__m=5, cmutexWaitR__p=5, croomEmptySignalR__m=4, croomEmptySignalR__p=4, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=5, croomEmptyWaitR__p=5, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 42:		[9] -> Invariant OK: {cREADERSDOWN__p=5, cREADERSUP__p=5, cmutexSignalR2__m=4, cmutexSignalR2__p=4, cmutexSignalR__m=5, cmutexSignalR__p=5, cmutexWaitR2__m=5, cmutexWaitR2__p=5, cmutexWaitR__m=5, cmutexWaitR__p=5, croomEmptySignalR__m=5, croomEmptySignalR__p=5, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=5, croomEmptyWaitR__p=5, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 42:		[9] -> Invariant OK: {cREADERSDOWN__p=5, cREADERSUP__p=5, cmutexSignalR2__m=5, cmutexSignalR2__p=5, cmutexSignalR__m=5, cmutexSignalR__p=5, cmutexWaitR2__m=5, cmutexWaitR2__p=5, cmutexWaitR__m=5, cmutexWaitR__p=5, croomEmptySignalR__m=5, croomEmptySignalR__p=5, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=5, croomEmptyWaitR__p=5, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=1
// 43:		[9] -> Invariant OK: {cREADERSDOWN__p=5, cREADERSUP__p=5, cmutexSignalR2__m=5, cmutexSignalR2__p=5, cmutexSignalR__m=5, cmutexSignalR__p=5, cmutexWaitR2__m=5, cmutexWaitR2__p=5, cmutexWaitR__m=6, cmutexWaitR__p=6, croomEmptySignalR__m=5, croomEmptySignalR__p=5, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=5, croomEmptyWaitR__p=5, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 43:		[9] -> Invariant OK: {cREADERSDOWN__p=5, cREADERSUP__p=6, cmutexSignalR2__m=5, cmutexSignalR2__p=5, cmutexSignalR__m=5, cmutexSignalR__p=5, cmutexWaitR2__m=5, cmutexWaitR2__p=5, cmutexWaitR__m=6, cmutexWaitR__p=6, croomEmptySignalR__m=5, croomEmptySignalR__p=5, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=6, croomEmptyWaitR__p=6, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 43:		[9] -> Invariant OK: {cREADERSDOWN__p=5, cREADERSUP__p=6, cmutexSignalR2__m=5, cmutexSignalR2__p=5, cmutexSignalR__m=6, cmutexSignalR__p=6, cmutexWaitR2__m=5, cmutexWaitR2__p=5, cmutexWaitR__m=6, cmutexWaitR__p=6, croomEmptySignalR__m=5, croomEmptySignalR__p=5, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=6, croomEmptyWaitR__p=6, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=1
// 43:		[9] -> Obtenido valor: 10
// 44:		[9] -> Invariant OK: {cREADERSDOWN__p=5, cREADERSUP__p=6, cmutexSignalR2__m=5, cmutexSignalR2__p=5, cmutexSignalR__m=6, cmutexSignalR__p=6, cmutexWaitR2__m=6, cmutexWaitR2__p=6, cmutexWaitR__m=6, cmutexWaitR__p=6, croomEmptySignalR__m=5, croomEmptySignalR__p=5, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=6, croomEmptyWaitR__p=6, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 44:		[9] -> Invariant OK: {cREADERSDOWN__p=6, cREADERSUP__p=6, cmutexSignalR2__m=5, cmutexSignalR2__p=5, cmutexSignalR__m=6, cmutexSignalR__p=6, cmutexWaitR2__m=6, cmutexWaitR2__p=6, cmutexWaitR__m=6, cmutexWaitR__p=6, croomEmptySignalR__m=6, croomEmptySignalR__p=6, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=6, croomEmptyWaitR__p=6, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 45:		[9] -> Invariant OK: {cREADERSDOWN__p=6, cREADERSUP__p=6, cmutexSignalR2__m=6, cmutexSignalR2__p=6, cmutexSignalR__m=6, cmutexSignalR__p=6, cmutexWaitR2__m=6, cmutexWaitR2__p=6, cmutexWaitR__m=6, cmutexWaitR__p=6, croomEmptySignalR__m=6, croomEmptySignalR__p=6, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=6, croomEmptyWaitR__p=6, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=1
// 45:		[9] -> Invariant OK: {cREADERSDOWN__p=6, cREADERSUP__p=6, cmutexSignalR2__m=6, cmutexSignalR2__p=6, cmutexSignalR__m=6, cmutexSignalR__p=6, cmutexWaitR2__m=6, cmutexWaitR2__p=6, cmutexWaitR__m=7, cmutexWaitR__p=7, croomEmptySignalR__m=6, croomEmptySignalR__p=6, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=6, croomEmptyWaitR__p=6, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 45:		[9] -> Invariant OK: {cREADERSDOWN__p=6, cREADERSUP__p=7, cmutexSignalR2__m=6, cmutexSignalR2__p=6, cmutexSignalR__m=6, cmutexSignalR__p=6, cmutexWaitR2__m=6, cmutexWaitR2__p=6, cmutexWaitR__m=7, cmutexWaitR__p=7, croomEmptySignalR__m=6, croomEmptySignalR__p=6, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=7, croomEmptyWaitR__p=7, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 46:		[9] -> Invariant OK: {cREADERSDOWN__p=6, cREADERSUP__p=7, cmutexSignalR2__m=6, cmutexSignalR2__p=6, cmutexSignalR__m=7, cmutexSignalR__p=7, cmutexWaitR2__m=6, cmutexWaitR2__p=6, cmutexWaitR__m=7, cmutexWaitR__p=7, croomEmptySignalR__m=6, croomEmptySignalR__p=6, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=7, croomEmptyWaitR__p=7, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=1
// 46:		[9] -> Obtenido valor: 10
// 46:		[9] -> Invariant OK: {cREADERSDOWN__p=6, cREADERSUP__p=7, cmutexSignalR2__m=6, cmutexSignalR2__p=6, cmutexSignalR__m=7, cmutexSignalR__p=7, cmutexWaitR2__m=7, cmutexWaitR2__p=7, cmutexWaitR__m=7, cmutexWaitR__p=7, croomEmptySignalR__m=6, croomEmptySignalR__p=6, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=7, croomEmptyWaitR__p=7, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 47:		[9] -> Invariant OK: {cREADERSDOWN__p=7, cREADERSUP__p=7, cmutexSignalR2__m=6, cmutexSignalR2__p=6, cmutexSignalR__m=7, cmutexSignalR__p=7, cmutexWaitR2__m=7, cmutexWaitR2__p=7, cmutexWaitR__m=7, cmutexWaitR__p=7, croomEmptySignalR__m=7, croomEmptySignalR__p=7, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=7, croomEmptyWaitR__p=7, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 47:		[9] -> Invariant OK: {cREADERSDOWN__p=7, cREADERSUP__p=7, cmutexSignalR2__m=7, cmutexSignalR2__p=7, cmutexSignalR__m=7, cmutexSignalR__p=7, cmutexWaitR2__m=7, cmutexWaitR2__p=7, cmutexWaitR__m=7, cmutexWaitR__p=7, croomEmptySignalR__m=7, croomEmptySignalR__p=7, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=7, croomEmptyWaitR__p=7, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=1
// 47:		[9] -> Invariant OK: {cREADERSDOWN__p=7, cREADERSUP__p=7, cmutexSignalR2__m=7, cmutexSignalR2__p=7, cmutexSignalR__m=7, cmutexSignalR__p=7, cmutexWaitR2__m=7, cmutexWaitR2__p=7, cmutexWaitR__m=8, cmutexWaitR__p=8, croomEmptySignalR__m=7, croomEmptySignalR__p=7, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=7, croomEmptyWaitR__p=7, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 48:		[9] -> Invariant OK: {cREADERSDOWN__p=7, cREADERSUP__p=8, cmutexSignalR2__m=7, cmutexSignalR2__p=7, cmutexSignalR__m=7, cmutexSignalR__p=7, cmutexWaitR2__m=7, cmutexWaitR2__p=7, cmutexWaitR__m=8, cmutexWaitR__p=8, croomEmptySignalR__m=7, croomEmptySignalR__p=7, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=8, croomEmptyWaitR__p=8, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 48:		[9] -> Invariant OK: {cREADERSDOWN__p=7, cREADERSUP__p=8, cmutexSignalR2__m=7, cmutexSignalR2__p=7, cmutexSignalR__m=8, cmutexSignalR__p=8, cmutexWaitR2__m=7, cmutexWaitR2__p=7, cmutexWaitR__m=8, cmutexWaitR__p=8, croomEmptySignalR__m=7, croomEmptySignalR__p=7, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=8, croomEmptyWaitR__p=8, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=1
// 48:		[9] -> Obtenido valor: 10
// 49:		[9] -> Invariant OK: {cREADERSDOWN__p=7, cREADERSUP__p=8, cmutexSignalR2__m=7, cmutexSignalR2__p=7, cmutexSignalR__m=8, cmutexSignalR__p=8, cmutexWaitR2__m=8, cmutexWaitR2__p=8, cmutexWaitR__m=8, cmutexWaitR__p=8, croomEmptySignalR__m=7, croomEmptySignalR__p=7, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=8, croomEmptyWaitR__p=8, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 49:		[9] -> Invariant OK: {cREADERSDOWN__p=8, cREADERSUP__p=8, cmutexSignalR2__m=7, cmutexSignalR2__p=7, cmutexSignalR__m=8, cmutexSignalR__p=8, cmutexWaitR2__m=8, cmutexWaitR2__p=8, cmutexWaitR__m=8, cmutexWaitR__p=8, croomEmptySignalR__m=8, croomEmptySignalR__p=8, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=8, croomEmptyWaitR__p=8, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 49:		[9] -> Invariant OK: {cREADERSDOWN__p=8, cREADERSUP__p=8, cmutexSignalR2__m=8, cmutexSignalR2__p=8, cmutexSignalR__m=8, cmutexSignalR__p=8, cmutexWaitR2__m=8, cmutexWaitR2__p=8, cmutexWaitR__m=8, cmutexWaitR__p=8, croomEmptySignalR__m=8, croomEmptySignalR__p=8, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=8, croomEmptyWaitR__p=8, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=1
// 50:		[9] -> Invariant OK: {cREADERSDOWN__p=8, cREADERSUP__p=8, cmutexSignalR2__m=8, cmutexSignalR2__p=8, cmutexSignalR__m=8, cmutexSignalR__p=8, cmutexWaitR2__m=8, cmutexWaitR2__p=8, cmutexWaitR__m=9, cmutexWaitR__p=9, croomEmptySignalR__m=8, croomEmptySignalR__p=8, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=8, croomEmptyWaitR__p=8, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 50:		[9] -> Invariant OK: {cREADERSDOWN__p=8, cREADERSUP__p=9, cmutexSignalR2__m=8, cmutexSignalR2__p=8, cmutexSignalR__m=8, cmutexSignalR__p=8, cmutexWaitR2__m=8, cmutexWaitR2__p=8, cmutexWaitR__m=9, cmutexWaitR__p=9, croomEmptySignalR__m=8, croomEmptySignalR__p=8, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=9, croomEmptyWaitR__p=9, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 50:		[9] -> Invariant OK: {cREADERSDOWN__p=8, cREADERSUP__p=9, cmutexSignalR2__m=8, cmutexSignalR2__p=8, cmutexSignalR__m=9, cmutexSignalR__p=9, cmutexWaitR2__m=8, cmutexWaitR2__p=8, cmutexWaitR__m=9, cmutexWaitR__p=9, croomEmptySignalR__m=8, croomEmptySignalR__p=8, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=9, croomEmptyWaitR__p=9, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=1
// 51:		[9] -> Obtenido valor: 10
// 51:		[9] -> Invariant OK: {cREADERSDOWN__p=8, cREADERSUP__p=9, cmutexSignalR2__m=8, cmutexSignalR2__p=8, cmutexSignalR__m=9, cmutexSignalR__p=9, cmutexWaitR2__m=9, cmutexWaitR2__p=9, cmutexWaitR__m=9, cmutexWaitR__p=9, croomEmptySignalR__m=8, croomEmptySignalR__p=8, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=9, croomEmptyWaitR__p=9, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 51:		[9] -> Invariant OK: {cREADERSDOWN__p=9, cREADERSUP__p=9, cmutexSignalR2__m=8, cmutexSignalR2__p=8, cmutexSignalR__m=9, cmutexSignalR__p=9, cmutexWaitR2__m=9, cmutexWaitR2__p=9, cmutexWaitR__m=9, cmutexWaitR__p=9, croomEmptySignalR__m=9, croomEmptySignalR__p=9, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=9, croomEmptyWaitR__p=9, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 52:		[9] -> Invariant OK: {cREADERSDOWN__p=9, cREADERSUP__p=9, cmutexSignalR2__m=9, cmutexSignalR2__p=9, cmutexSignalR__m=9, cmutexSignalR__p=9, cmutexWaitR2__m=9, cmutexWaitR2__p=9, cmutexWaitR__m=9, cmutexWaitR__p=9, croomEmptySignalR__m=9, croomEmptySignalR__p=9, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=9, croomEmptyWaitR__p=9, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=1
// 52:		[9] -> Invariant OK: {cREADERSDOWN__p=9, cREADERSUP__p=9, cmutexSignalR2__m=9, cmutexSignalR2__p=9, cmutexSignalR__m=9, cmutexSignalR__p=9, cmutexWaitR2__m=9, cmutexWaitR2__p=9, cmutexWaitR__m=10, cmutexWaitR__p=10, croomEmptySignalR__m=9, croomEmptySignalR__p=9, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=9, croomEmptyWaitR__p=9, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 52:		[9] -> Invariant OK: {cREADERSDOWN__p=9, cREADERSUP__p=10, cmutexSignalR2__m=9, cmutexSignalR2__p=9, cmutexSignalR__m=9, cmutexSignalR__p=9, cmutexWaitR2__m=9, cmutexWaitR2__p=9, cmutexWaitR__m=10, cmutexWaitR__p=10, croomEmptySignalR__m=9, croomEmptySignalR__p=9, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=10, croomEmptyWaitR__p=10, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 53:		[9] -> Invariant OK: {cREADERSDOWN__p=9, cREADERSUP__p=10, cmutexSignalR2__m=9, cmutexSignalR2__p=9, cmutexSignalR__m=10, cmutexSignalR__p=10, cmutexWaitR2__m=9, cmutexWaitR2__p=9, cmutexWaitR__m=10, cmutexWaitR__p=10, croomEmptySignalR__m=9, croomEmptySignalR__p=9, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=10, croomEmptyWaitR__p=10, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=1
// 53:		[9] -> Obtenido valor: 10
// 53:		[9] -> Invariant OK: {cREADERSDOWN__p=9, cREADERSUP__p=10, cmutexSignalR2__m=9, cmutexSignalR2__p=9, cmutexSignalR__m=10, cmutexSignalR__p=10, cmutexWaitR2__m=10, cmutexWaitR2__p=10, cmutexWaitR__m=10, cmutexWaitR__p=10, croomEmptySignalR__m=9, croomEmptySignalR__p=9, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=10, croomEmptyWaitR__p=10, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=0 mutex=0
// 53:		[9] -> Invariant OK: {cREADERSDOWN__p=10, cREADERSUP__p=10, cmutexSignalR2__m=9, cmutexSignalR2__p=9, cmutexSignalR__m=10, cmutexSignalR__p=10, cmutexWaitR2__m=10, cmutexWaitR2__p=10, cmutexWaitR__m=10, cmutexWaitR__p=10, croomEmptySignalR__m=10, croomEmptySignalR__p=10, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=10, croomEmptyWaitR__p=10, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=0
// 54:		[9] -> Invariant OK: {cREADERSDOWN__p=10, cREADERSUP__p=10, cmutexSignalR2__m=10, cmutexSignalR2__p=10, cmutexSignalR__m=10, cmutexSignalR__p=10, cmutexWaitR2__m=10, cmutexWaitR2__p=10, cmutexWaitR__m=10, cmutexWaitR__p=10, croomEmptySignalR__m=10, croomEmptySignalR__p=10, croomEmptySignalW__m=10, croomEmptySignalW__p=10, croomEmptyWaitR__m=10, croomEmptyWaitR__p=10, croomEmptyWaitW__m=10, croomEmptyWaitW__p=10} roomEmpty=1 mutex=1

//-------------------------------------------------
// Escenario con problemas 1: Los lectores no bajan roomEmpty hasta el segundo
// lector:
// jose@tantor7:~/docto/cclib$ java RW.TestRW
//      0:	[11] -> Invariant OK: {croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=0 mutex=1
//     13:	[11] -> Escrito valor: 1
//     14:		[9] -> Invariant OK: {cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=0 mutex=0
//     14:	[11] -> Invariant OK: {cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=1 mutex=0
//     15:		[9] -> Invariant OK: {cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=1 mutex=1
//     15:		[9] -> Obtenido valor: 1
//     16:	[11] -> >>>>> Illegal system state: cREWaitW+=2, cRESignalW=1, cMSignalR+=1,cMWaitR2=0{cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitW__m=2, croomEmptyWaitW__p=2} roomEmpty=0 mutex=1
//     16:	[11] -> ERROR EN WRITER: >>>>> Illegal system state: cREWaitW+=2, cRESignalW=1, cMSignalR+=1,cMWaitR2=0{cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitW__m=2, croomEmptyWaitW__p=2} roomEmpty=0 mutex=1

// -------------------------------------------------------------------
// Escenario con problemas 2: El semaforo roomEmpty ahora tiene credito 2.
//  0:	[9] -> Invariant OK: {cmutexWaitR__m=1, cmutexWaitR__p=1} roomEmpty=2 mutex=0
// 15:		[11] -> Invariant OK: {cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=1 mutex=0
// 15:		[11] -> Escrito valor: 1
// 15:	[9] -> Invariant OK: {cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=0 mutex=0
// 16:		[11] -> Invariant OK: {cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=1 mutex=0
// 16:	[9] -> Invariant OK: {cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=1, croomEmptyWaitW__p=1} roomEmpty=1 mutex=1
// 16:	[9] -> Obtenido valor: 1
// 17:		[11] -> >>>>> Illegal system state: cREWaitW+=2, cRESignalW=1, cMSignalR+=1,cMWaitR2=0{cmutexSignalR__m=1, cmutexSignalR__p=1, cmutexWaitR__m=1, cmutexWaitR__p=1, croomEmptySignalW__m=1, croomEmptySignalW__p=1, croomEmptyWaitR__m=1, croomEmptyWaitR__p=1, croomEmptyWaitW__m=2, croomEmptyWaitW__p=2} roomEmpty=0 mutex=1

// -----------------------------------------------------

// jose@tantor8:~/docto/cclib/cclib$ java RW.TestRW
//      0:	[11] -> Escrito valor: 1
//    121:		[9] -> ERROR EN READER: Illegal system state {
// "counters" : {cREADERSUP+ : 1, cmutexSignalR+ : 1, cmutexSignalR- : 1, cmutexWaitR+ : 1, cmutexWaitR- : 1, croomEmptyWaitR+ : 1, croomEmptyWaitR- : 1, croomEmptyWaitW+ : 1, croomEmptyWaitW- : 1}
// "semaphores" : {roomEmpty : 0, mutex : 1}
// }
//    122:	[11] -> ERROR EN WRITER: Illegal system state {
// "counters" : {cREADERSUP+ : 1, cmutexSignalR+ : 1, cmutexSignalR- : 1, cmutexWaitR+ : 1, cmutexWaitR- : 1, croomEmptySignalW+ : 1, croomEmptySignalW- : 1, croomEmptyWaitR+ : 1, croomEmptyWaitR- : 1, croomEmptyWaitW+ : 2, croomEmptyWaitW- : 2}
//  "semaphores" : {roomEmpty : 0, mutex : 1}
